language: rust

rust:
  - stable
  - beta

script: cargo test

matrix:
  include:
    - rust: nightly
      script:
        - cargo test
        - cargo test --benches --release
    - rust: 1.31.0
      script: cargo check
    - rust: nightly
      name: Clippy
      script:
        - rustup component add clippy || travis_terminate 0
        - cargo clippy -- -Dclippy::all
